### ISSUE TITLE
which ImageMagick version?

### ISSUE THREAD

**Issue by msccto** [viniciusfbb/image-magick#1]
Hi,

I'm currently testing the integration of ImageMagick into my project and stumbled accross this library.
However, I can't get it working correctly and I believe this is because in the redist folder there is ImageMagick v7.0.9 but as far as I understand the code it is based on v6.9.
Eg. the MagicWand record defined in ImageMagick.Wand.pas doesn't match the structure defined in (latest v7.1) magick-wand-private.h
Do I miss something?
Appreciate any help

Thanks,
Matt

**Comment by viniciusfbb** [comment]
Yes, the code was based on previous versions, but anyway in the last tests it was working in the redist version.

What exactly will you use ImageMagick for? I ask this because this repository will probably be archived, as skia4delphi has the most features and is much simpler, faster and crossplatform.

**Comment by msccto** [comment]
Thank you so much for your quick reply.

So far I only tested the demo application and basically it works. It correctly converts and resizes input_image.png to a jpg file.
However, I noticed that the internal field FMagickWand looks strange in the debugger after the input file has been loaded with MagickReadImageBlob:
![2021-09-01_08h11_56](https://user-images.githubusercontent.com/89782408/131620887-a52acd66-ab00-4d52-ba20-ba94f9859623.jpg)

Another problem happens if I replace input_image.png with eg. testfile.txt to force an exception in MagickReadImageBlob.
In CheckMagick function the exception gets correctly loaded from ImageMagick via MagickGetException and then displayed, however the whole application crashes afterwards with an access violation error. Because in my application I have to handle these kind of errors without crashing the application this is a more serious problem for me.

I tried with ImageMagick from the redist folder (ImageMagick-7.0.9-Q16) as well as with the legacy version ImageMagick-6.9.12-Q16-HDRI and Delphi 10.3.

Do you have any idea what I might be doing wrong?


>What exactly will you use ImageMagick for? I ask this because this repository will probably be archived, as skia4delphi has the most features and is much simpler, faster and crossplatform.

 I'm developing a scan application and need to perform image processing functions, apply filters and convert from one format to another (eg. tiff->jpg). As far as I have seen skia doesn't support these functions ;-(

**Comment by viniciusfbb** [comment]
It has to be investigated further, but I don't have time right now.

> I'm developing a scan application and need to perform image processing functions, apply filters and convert from one format to another (eg. tiff->jpg). As far as I have seen skia doesn't support these functions ;-(

You can do all this with skia, load image, resize, crop, encode in another format, apply color filters, and much more, and without having to install anything like image magick does. If you want I can help you make a little demo, but you can find many sample (mainly with skiasharp) that you can base.

**Comment by msccto** [comment]
Of course I understand that you don't have time right now, thank you so much for your great work so far!!!

Reg. skia I will take a look. For sure it would be great if you could give me a little demo program as a starting point, eg. showing how to read jpg and convert to another format.

Again, appreciate your help.

**Comment by viniciusfbb** [comment]
The TSKStreamAdapter (which you will need) have one bug. We will fix it and others minor issues in a week and then I will make a simple demo for you.

**Comment by viniciusfbb** [comment]
@msccto We released the skia4delphi v2 and added encode/decode example in sample. See one example:

https://github.com/viniciusfbb/skia4delphi#webp

If you have any question, just open a issue there.

I'm going to archive this repository now.
